version: "3.1"
assistant_id: test-clean-output
language: en

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 10
  learning_rate: 0.001
  batch_size: [64, 256]
  transformer_size: 256
  validation_split: 0.15
  evaluate_every_number_of_epochs: 1
  early_stopping:
    enabled: true
    monitor: "val_t_loss"
    patience: 5
    min_delta: 0.001
