language: en

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 50
  learning_rate: 0.001
  batch_size: [64, 256]
  transformer_size: 256
assistant_id: 20250825-165717-cerulean-whippet
